namespace Karin.PoolingSystem
{
    public enum PoolingType
    {
        HoneyRiceCake,
        Walnut,
        Yakgwa,
        Boss_SongPyeon,
        Dango,
        Manjuu,
        Bamboo,
        Boss_Pudding,
        Donut,
        MarshMallow,
        Waffle,
        Boss_Cupcake,
        Macaroon,
        Tart,
        Cannele,
        Boss_Ferrero,
        MiniBoss_Madeleine,
        MiniBoss_Pretzel,
        Effect_Slash,
        Tower_MochiBase,
        Effect_Explosion,
        Effect_Explosion1,
        Effect_StarLight,
    }
}